version: '3.8'
services:
  php:
    build: ./_docker
    container_name: php
    working_dir: /app
    volumes:
      - ./src/app:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./src/app:/app
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "80:80"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
